### ISSUE TITLE
텍스트 내에 기능 추가

### ISSUE THREAD

**Issue by yoosoo-won** [fastcampusgit/fastcomposer#107]
* 텍스트를 블럭으로 선택시 텍스트 크기, 색상, 밑줄, 기울기, 볼드, 취소선이 적용가능하도록 추가합니다.

**Comment by iolo** [comment]
밑줄,이탤릭,취소선...은 마크다운을 직접 입력하는 방식으로 해결할 계획이었습니다.
같은 블럭 내에 폰트 크기, 색상 등을 임의로 지정하는 것은 허용하지 않을 계획이었습니다. 디자인이 망가질테니까요.
그럼에도 불구하고...
굳이 그렇게 해야겠다면... param type에 html을 추가하고... html타입에 대해서는  wysiwyg 에디터를 사용할 수 있겠죠.

**Comment by yoosoo-won** [comment]
텍스트 크기 -> 대부분 클래스로 대응
색상(배경 및 글자) -> inline 형태로 대응
그외(밑줄, 기울기, 볼드, 취소선 등) 간단한 테그 사용으로 대응.
다른 기획이나 변경사항이 생기면 다시 그에 맞게 대응합니다.
