### ISSUE TITLE
How apply CSS?

### ISSUE THREAD

**Issue by akiraei** [fastcampusgit/fastcomposer#17]
1. <style></style>
2. scss and webpack
3. ...?!

**Comment by soomtong** [comment]
VUE 관행 대로 그리고 본 프로젝트는 독립적인 프로젝트이니 

1. <style lang=scss>

정도로 하는게 좋을 것 같아요.

**Comment by akiraei** [comment]
@gotppetto 어떻게 생각하십니까?

**Comment by akiraei** [comment]
return 

1.<style lang=scss>
