### ISSUE TITLE
editor 영역 layers와 분리, preview영역위에서 편집모드 지원

### ISSUE THREAD

**Issue by yoosoo-won** [fastcampusgit/fastcomposer#22]
- block-item별로 존재하던것을 block-form을 하나의 영역(preview)안에서 편집하도록 수정
- preview영역위에서 drag&drop을 자유롭게 이동하며 편집 가능

**Comment by iolo** [comment]
하나의 영역 이름은 preview가 아니고 editor 겠죠^^

기존 방식을 off-the-spot(자리에서 벗어나서), 새 방식은 on-the-spot(그 자리에서) 이라고 합니다.
