### ISSUE TITLE
axios dependency 제거(또는 devDependencies 로 이동)

### ISSUE THREAD

**Issue by iolo** [fastcampusgit/fastcomposer#51]
ajax가 필요한 경우에는 컴포넌트를 사용하는 쪽에서 알아서 해야 합니다.
쓴다면 test case나 샘플 정도일 거 같은데... 그렇다면 dev dependencies로 옮길 수 있을 듯.

**Comment by yoosoo-won** [comment]
말씀하신것처럼 지금 axios를 따로 사용하지는 않습니다. 최대한 ajax를 통신을 지양하는 방향으로 맞춰보겠습니다.
