### ISSUE TITLE
npm run serve (npm run build) 가 동작하지 않음

### ISSUE THREAD

**Issue by iolo** [fastcampusgit/fastcomposer#69]
`npm run serve`가 동작을 안해서 살펴보니...

#67 에서 `layouts_bak`은 `layouts`로 원복하지 않고 그냥 삭제해버렸네요.

**Comment by yoosoo-won** [comment]
아직 문제가 있는거같아서 제가 받겠습니다.

**Comment by yoosoo-won** [comment]
아 노드 재설치하니 정상적으로 뜨네요...;;;;
