### ISSUE TITLE
텍스트 입력 후 엔터를 누르면 창이 새로고침됩니다

### ISSUE THREAD

**Issue by cjstk7168** [fastcampusgit/fastcomposer#78]

**Comment by cjstk7168** [comment]
재현이 안되네요.. 좀 더 확인해볼게요

**Comment by yoosoo-won** [comment]
> 재현이 안되네요.. 좀 더 확인해볼게요

정확한 이유는 모르겠지만 layouts 중 x박스로 image 업로드 영역에 대해서만 발생하고 있는것으로 파악이되며, x박스가 표시되는 현상을 수정하면 관련 버그가 사라지고있습니다.

**Comment by yoosoo-won** [comment]
일단 관련문제가 사라져서 문제가 다시 발생하면 재오픈하여 대응하겠습니다.
