### ISSUE TITLE
layout: 021 (시간표시 오류사항)

### ISSUE THREAD

**Issue by cjstk7168** [fastcampusgit/fastcomposer#79]
<img width="449" alt="스크린샷 2019-09-05 오전 11 03 53" src="https://user-images.githubusercontent.com/39257313/64306209-f14acd00-cfcc-11e9-8c95-d43a0063a2b2.png">
1. 시간+날짜를 선택할 때 picker에는 날짜선택만 가능합니다.

<img width="326" alt="스크린샷 2019-09-05 오전 11 03 23" src="https://user-images.githubusercontent.com/39257313/64306227-00317f80-cfcd-11e9-85a1-f5f88d04ee7a.png">
<img width="1919" alt="스크린샷 2019-09-05 오전 11 03 40" src="https://user-images.githubusercontent.com/39257313/64306229-032c7000-cfcd-11e9-81e3-df83f56b216b.png">
2. 날짜와 시간을 입력하엿는데, 코스 상페에서 보면 시간이 안나와요
(제가 사용법을 몰라서 그런것일 수 도..)

<img width="1673" alt="스크린샷 2019-09-05 오전 11 03 46" src="https://user-images.githubusercontent.com/39257313/64306249-13444f80-cfcd-11e9-9a50-20d7fb828970.png">

3. 시간표시하는 부분이 다른 영역보다 아래에 있어서 가려집니다.

4. 사용하지않는 SectionTitle을 입력받습니다.

**Comment by yoosoo-won** [comment]
전반적인 기획이 다시 필요해보입니다.

**Comment by yoosoo-won** [comment]
제플린 디자인을 적용하여 이슈 닫습니다.
