### ISSUE TITLE
layout 002: 백그라운드컬러가 적용이 안됩니다

### ISSUE THREAD

**Issue by cjstk7168** [fastcampusgit/fastcomposer#80]
백그라운드 컬러 위에 이미지가 올라가고 있습니다.

백그라운드 컬러 설정이 필요하지 않을 것 같아요.

**Comment by yoosoo-won** [comment]
> 백그라운드 컬러 위에 이미지가 올라가고 있습니다.
> 
> 백그라운드 컬러 설정이 필요하지 않을 것 같아요.

이미지를 사용하지 않고, 컬러 사용만 하는경우로 알고있습니다. 만약 이미지 뒤에 항상 100% 채워야한다면 따로 작업이 필요해보입니다.

**Comment by cjstk7168** [comment]
음.. 그렇다면 아무 이미지를 선택하지 않았을때 자동으로 플레이스홀더 이미지가 들어가는데 이부분 수정이 필요할것같습니다.

**Comment by yoosoo-won** [comment]
> 그렇다면 아무 이미지를 선택하지 않았을때 자동으로 플레이스홀더 이미지가 들어가는데 이부분 수정이 필요할것같습니다.

이미지가 따로 정해지기전까지는 현재를 유지하고 정해지면 교체하는식으로가는것이 맞을듯합니다.

**Comment by yoosoo-won** [comment]
제플린에 이미지 사이즈보다 넘어가면 background-color가 적용되도록 되어 제플린 기준으로 적용하였습니다.
zpl.io/V0JqAXm
