### ISSUE TITLE
컴포저 편집 패널 좌측 고정

### ISSUE THREAD

**Issue by yoosoo-won** [fastcampusgit/fastcomposer#94]
* 편집 패널에 draggable기능을 제거하고 우측에 고정

**Comment by soomtong** [comment]
개인적인 견해로 0.43 릴리즈는 drag 핸들러만 조절해서 
```
[드래그핸들]    [감추기핸들]
     --- 콘텐트 ---
         ....
```
적용하고 
실제 사용자에게 피드백을 좀 받고 진행하는게 어떨까 합니다.
draggable 에 대한 불편이 아니였으니까요.

**Comment by yoosoo-won** [comment]
네 말씀주신것처럼 피드백좀 받고 진행하는것으로 진행하겠습니다.
